# 项目相关配置
kairuite:
  #名称
  name: KaiRuiTe
  #版本
  version: 1.0.0
  #版权年份
  copyrightYear: 2018
  #头像上传路径
  profile: D:/profile/
#开发环境配置
server:
  #端口
  port: 80
  tomcat:
    uri-encoding: utf-8
#日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug
#Spring配置
spring:
  thymeleaf:
    mode: HTML
    encoding: utf-8
    cache: false
  messages:
    #国际化资源文件路径
    basename: i18n/messages
  profiles: 
    active: druid
  #文件上传
  servlet:
     multipart:
       max-file-size:  30MB
       max-request-size:  30MB
  devtools:
    restart:
      #禁用devtools模块的热部署功能
      enabled: true